# Generated by Django 3.0 on 2021-03-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='takenquiz',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
